### ISSUE TITLE
Doctrine\Common\Cache\Cache used despite of requiring doctrine/cache

### ISSUE THREAD

**Issue by simPod** [nettrine/cache#6]
`Doctrine\Common\Cache\Cache` was dropped from Doctrine\Common and replaced by classes in correctly required `doctrine/cache`.

Doctrine\Common is still used in the code here though, rendering it not working.

https://github.com/nettrine/cache/search?q=Doctrine%5CCommon&unscoped_q=Doctrine%5CCommon

> Service 'nettrine.annotations.reader' (type of Doctrine\Common\Annotations\Reader): Service of type 'Doctrine\Common\Cache\Cache' not found.

**Comment by f3l1x** [comment]
Thanks @simPod. Which version of doctrine is affected by dropping `Doctrine\Common`?

**Comment by simPod** [comment]
Guess it's this one https://github.com/doctrine/cache/releases/tag/1.10.0

**Comment by f3l1x** [comment]
Thanks, I will take a look.

**Comment by f3l1x** [comment]
Resolved
